name: CI Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and run docker-compose stack
        run: docker-compose up --build --abort-on-container-exit

      - name: Show test logs
        run: docker compose logs tests

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: ./Pruebas/.pytest_cache
